# Generated by Django 5.1.2 on 2024-12-10 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassPost',
        ),
    ]
